In [1]:
import numpy as np
import pandas as pd
import random

In [2]:
csv = pd.read_csv("travel_safe.csv")

In [3]:
csv

latitude   longitude       time  crimerate  weatherconditionid  \
0   42.490802 -115.599914  15.408760   0.051682                   1   
1   54.014286  -30.902542   2.019359   0.531355                   1   
2   49.639879  -75.990163   3.879089   0.540635                   1   
3   46.973170  -48.800103  21.565301   0.637430                   4   
4   38.120373    7.059306  14.554297   0.726091                   1   
..        ...         ...        ...        ...                 ...   
95  44.875912  -71.110660  12.533838   0.930757                   5   
96  45.454657  -18.366205  18.479845   0.858413                   2   
97  43.550820    5.595436   5.179705   0.428994                   4   
98  35.508383    4.192099  14.949371   0.750871                   5   
99  37.157829  -10.817424   2.048339   0.754543                   5   

    trafficdensityid  safestateid  
0                  1            1  
1                  3            1  
2                  1            2  
3                  2            1  
4                  1            2  
..               ...          ...  
95                 1            2  
96                 1            2  
97                 2            1  
98                 2            1  
99                 3            1  

[100 rows x 7 columns]

In [4]:
y_view = csv.iloc[:,-1]
y_view

0     1
1     1
2     2
3     1
4     2
     ..
95    2
96    2
97    1
98    1
99    1
Name: safestateid, Length: 100, dtype: int64

In [109]:
y = csv.iloc[:, -1].to_numpy().reshape(-1, 1)
y = np.where(y == 1, 0, 1)

In [111]:
X = csv[["latitude", "longitude"]].to_numpy()

In [113]:
data = list(zip(X, y))

In [114]:
random.seed(42)
random.shuffle(data)

In [115]:
split_idx = int(0.8 * len(data))
print(split_idx)
train_data = data[:split_idx]
test_data = data[split_idx:]

80


In [116]:
X_train, y_train = zip(*train_data)
X_test, y_test = zip(*test_data)

In [117]:
X_train = pd.DataFrame(np.array(X_train), columns=["latitude", "longitude"])
X_train = X_train[['latitude', 'longitude']].to_numpy()
X_test = pd.DataFrame(np.array(X_test), columns=["latitude", "longitude"])
X_test = X_test[['latitude', 'longitude']].to_numpy()

In [118]:
X_train

array([[  35.68777042,  -50.38520918],
       [  44.9035382 ,  -84.75047858],
       [  49.26489574,    5.61020611],
       [  49.16145156, -109.22281262],
       [  45.85392166,   -3.05765062],
       [  54.39169256,    7.15722404],
       [  54.01428613,  -30.90254242],
       [  50.44489539,  -25.14098934],
       [  38.6680902 ,    2.00448263],
       [  42.16931457,   11.14219842],
       [  51.30922857,  -88.29059147],
       [  35.41168989,  -79.43479659],
       [  53.4374847 ,  -86.11226199],
       [  36.76985004,  -25.90102336],
       [  35.11044234,  -48.30697184],
       [  48.25044569, -114.83582737],
       [  45.93420559, -112.79297483],
       [  50.21570097,    6.058528  ],
       [  50.42540693,  -23.26871667],
       [  36.95344228,  -21.57734575],
       [  47.15089704,  -61.56245956],
       [  37.78987721,    5.45278199],
       [  36.30103186, -103.21884857],
       [  45.45465659,  -18.36620496],
       [  52.26206852,  -72.25071085],
       [  38.69708911,  -

In [119]:
y_train = pd.DataFrame(np.array(y_train), columns=["safestateid"])
y_train = y_train[['safestateid']].to_numpy()
y_test = pd.DataFrame(np.array(y_test), columns=["safestateid"])
y_test = y_test[['safestateid']].to_numpy()

In [120]:
y_train

array([[0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [0],
       [0],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
       [0],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0]])

In [121]:
# Calculating average (arithmetic mean) of an array or a specific axis of an array
# Note for axis
# axis = None (default): Computes the mean of the entire array.
# axis = 0: Computes the mean along the columns.
# axis = 1: Computes the mean along the rows.
X_mean = np.mean(X_train, axis=0)

In [122]:
X_mean

array([ 44.05229803, -49.79648732])

In [123]:
# np.std (standard deviation) of an array or along a specified axis.
# details of formulation please refer to: [formulation/std] in this project.
X_std = np.std(X_train, axis=0)

In [124]:
# applying z-score formulation to scaling data
# details of below formulation refer to: [formulation/scale] in this project.
X_train = (X_train - X_mean) / X_std

In [125]:
X_train = np.hstack((np.ones((X_train.shape[0], 1)), X_train))

In [126]:
X_train

array([[ 1.        , -1.40628989, -0.01466324],
       [ 1.        ,  0.14311513, -0.87059574],
       [ 1.        ,  0.87637029,  1.38000925],
       [ 1.        ,  0.85897869, -1.48012584],
       [ 1.        ,  0.30289877,  1.16411976],
       [ 1.        ,  1.73831526,  1.41854068],
       [ 1.        ,  1.67486364,  0.47058969],
       [ 1.        ,  1.07475825,  0.61409215],
       [ 1.        , -0.90522232,  1.29020184],
       [ 1.        , -0.31657742,  1.51779406],
       [ 1.        ,  1.22007465, -0.95876899],
       [ 1.        , -1.45270605, -0.73819855],
       [ 1.        ,  1.57788865, -0.90451355],
       [ 1.        , -1.22436478,  0.59516205],
       [ 1.        , -1.50335343,  0.03709922],
       [ 1.        ,  0.70581543, -1.61992866],
       [ 1.        ,  0.31639654, -1.56904753],
       [ 1.        ,  1.03622484,  1.39117556],
       [ 1.        ,  1.07148174,  0.66072466],
       [ 1.        , -1.19349825,  0.70285148],
       [ 1.        ,  0.52095332, -0.293

In [127]:
X_train.shape

(80, 3)

In [128]:
print(X_train.shape)
print(y_train.shape)

(80, 3)
(80, 1)


In [129]:
def sigmoid(s):
    return 1 / (1 + np.exp(-s))

In [130]:
def prod(w, X):
    '''
    X: a 3d array of shape (N, d). N datapoint, each with size d
    w: a 1d numpy array of shape (d)
    '''
    return sigmoid(X.dot(w))

In [131]:
# refer to: formulation/logistic/loss_function.png
def loss(w, X, y, lamda):
    z = prod(w, X)
    return - np.mean(y * np.log(z) + (1 - y) * np.log(1 - z) + 0.5 * lamda * np.sum(w[1:] ** 2))

In [132]:
def logistic_sigmoid_regression(w_init, X, y, lamda = 0.0001, learning_rate = 0.05, epochs = 1000):
    w_list = [w_init]
    loss_history = [loss(w_init, X, y, lamda)]
    epoch = 0
    n = X.shape[1]
    d = X.shape[0]
    while epoch < epochs:
        mix_idx = np.random.permutation(n)
        for i in mix_idx:
            # size of xi is (3, 1)
            xi = X[i,:]
            yi = y[i]
            zi = prod(w_list[-1].T, xi)
            w = w_list[-1] - learning_rate * ((zi - yi) * xi + lamda * w_list[-1])
            w_list.append(w)
            if np.linalg.norm(w_list[-1] - w_list[-2]) / d < 1e-6:
                break
            epoch += 1
        loss_history.append(loss(w_list[-1], X, y, lamda))
    return w_list, loss_history


In [133]:
w_init = np.random.randn(X_train.shape[1])
w_init

array([ 0.94176945,  1.1819783 , -0.99510365])

In [134]:
w, l = logistic_sigmoid_regression(w_init, X_train, y_train, epochs = 5000)

In [135]:
w[-1]

array([-2.10215179,  2.88559472,  3.84475871])

In [136]:
l

[np.float64(0.9803754127178311),
 np.float64(0.9716713397392056),
 np.float64(0.9641134810186268),
 np.float64(0.9575724057025177),
 np.float64(0.9519983357562422),
 np.float64(0.9472500518836039),
 np.float64(0.9434628524835652),
 np.float64(0.940495886162413),
 np.float64(0.9382049927316533),
 np.float64(0.9366323610773907),
 np.float64(0.9358272783220236),
 np.float64(0.9356512785480351),
 np.float64(0.93605928101758),
 np.float64(0.9370034950845562),
 np.float64(0.9384357784948443),
 np.float64(0.9403264694999172),
 np.float64(0.9426261076413531),
 np.float64(0.9453034971655464),
 np.float64(0.9482578445856796),
 np.float64(0.9515264743581292),
 np.float64(0.9551414852727297),
 np.float64(0.959006312767793),
 np.float64(0.9630990588351301),
 np.float64(0.9673375365163939),
 np.float64(0.9718085235472185),
 np.float64(0.9763928078415257),
 np.float64(0.9811182393866993),
 np.float64(0.9859637267350007),
 np.float64(0.990917729415417),
 np.float64(0.9960038061016502),
 np.float64(1.0

In [137]:
result = sigmoid(np.dot(X_train, w[-1]))
result.tolist()

[0.0019922207568682008,
 0.00645509139559171,
 0.9967714882044122,
 0.004897045567813836,
 0.9625886089308849,
 0.9997678438497252,
 0.9894406670625079,
 0.9664372988368128,
 0.5612553069741752,
 0.943741012532846,
 0.09382966126864717,
 0.00010810839915183076,
 0.26373583643507514,
 0.03399623791725061,
 0.0018373664365525695,
 0.0018445211355372112,
 0.0007299759252289378,
 0.9980475335175768,
 0.9715304404132329,
 0.05500218459341925,
 0.15114953854290283,
 0.5375325266039195,
 1.706614985205909e-05,
 0.830332783919936,
 0.4330327794028453,
 0.00045842158006160957,
 0.3020034515521189,
 0.42252719119663423,
 0.6017781403243253,
 0.6263461744890554,
 0.01316881221800315,
 0.19290597786020955,
 0.42627413840647455,
 0.07095213616335522,
 0.9081704885085904,
 0.0010199972171133086,
 0.25404386350430563,
 0.10356590113140297,
 0.22912563921087112,
 0.999341263291183,
 0.035374319284197,
 0.00027833786980140807,
 0.9834129506197723,
 0.7048806429681747,
 0.9498203456207989,
 0.0005265462

In [138]:
result.reshape(-1,1)

array([[1.99222076e-03],
       [6.45509140e-03],
       [9.96771488e-01],
       [4.89704557e-03],
       [9.62588609e-01],
       [9.99767844e-01],
       [9.89440667e-01],
       [9.66437299e-01],
       [5.61255307e-01],
       [9.43741013e-01],
       [9.38296613e-02],
       [1.08108399e-04],
       [2.63735836e-01],
       [3.39962379e-02],
       [1.83736644e-03],
       [1.84452114e-03],
       [7.29975925e-04],
       [9.98047534e-01],
       [9.71530440e-01],
       [5.50021846e-02],
       [1.51149539e-01],
       [5.37532527e-01],
       [1.70661499e-05],
       [8.30332784e-01],
       [4.33032779e-01],
       [4.58421580e-04],
       [3.02003452e-01],
       [4.22527191e-01],
       [6.01778140e-01],
       [6.26346174e-01],
       [1.31688122e-02],
       [1.92905978e-01],
       [4.26274138e-01],
       [7.09521362e-02],
       [9.08170489e-01],
       [1.01999722e-03],
       [2.54043864e-01],
       [1.03565901e-01],
       [2.29125639e-01],
       [9.99341263e-01],


In [140]:
y_train

array([[0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [0],
       [0],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
       [0],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0]])

IndexError: index 1 is out of bounds for axis 1 with size 1